name = "Nice Dream"
description = ""
street_address = "56778 29 Palms Highway"
locality = "Yucca Valley"
region = "CA"
postal_code = "92284"
country = "US"
phone = "+1 760-239-7919"
cuisine = ""
price_range = ""
hours_note = '<em>Coffee &amp; tea, pastries, and ice cream are served all day. Lunch service runs 11am - 3pm; dinner service runs 5:30 - 9pm (last seating 8pm). Reservations for dinner are not required, but strongly encouraged. </em><a href="sushi-reservations.html"><strong><em>Book here</em></strong></a><em>.</em>'

[[hours]]
closes = "21:00"
days = "Th-Sa"
label = "Thursday-Saturday"
opens = "08:00"

[[hours]]
closes = "16:00"
days = "Su"
label = "Sunday"
opens = "8:00"
