blurb = """
Nice Dreams of Sushi is this season's dinner concept — fish-forward, carefully sourced,
and made with a lot of care. Our cocktail bar, Sugar Water, is making its much anticipated
debut, and cocktails (NA + alcoholic) will be available for our guests. If you have
questions about the menu or allergens, email us at
[hello<span>&#64;</span>nice-dream.com](mailto:hello@nice-dream.com)"""
