// AUTO-GENERATED by archival - do not edit.

/** An uploaded file. `url` is "" until something has been uploaded. */
export interface ArchivalFile {
  display_type: "image" | "video" | "audio" | "upload";
  filename: string;
  sha: string;
  mime: string;
  name?: string;
  description?: string;
  url: string;
}

/** A `meta` field: free-form TOML, converted to JSON. */
export type ArchivalMeta =
  | string
  | number
  | boolean
  | null
  | ArchivalMeta[]
  | { [key: string]: ArchivalMeta };

export interface AboutObject {
  /** `<object name>/<file name>` this object was read from. */
  path: string;
  /** The object's `order`, or null when it is unordered. */
  order: number | null;
  body: string | null;
}

export interface LunchObject {
  /** `<object name>/<file name>` this object was read from. */
  path: string;
  /** The object's `order`, or null when it is unordered. */
  order: number | null;
  sample_menu: ArchivalFile | null;
}

export interface DinnerObject {
  /** `<object name>/<file name>` this object was read from. */
  path: string;
  /** The object's `order`, or null when it is unordered. */
  order: number | null;
  sample_menu: ArchivalFile | null;
  blurb: string | null;
  blurb_note: string | null;
  /**
   * Reservations — carriers/reservations and pages/reservations.liquid both read these.
   * minutes between seatings
   */
  slot_minutes: number | null;
  /** how long a booking holds its table, in minutes */
  hold_minutes: number | null;
  /** how many service weekends ahead the form offers */
  weekends_ahead: number | null;
  /** 2-tops are numbered 1..two_tops and combine in adjacent pairs (1/2, 3/4, …) for parties of 3–4 */
  two_tops: number | null;
  /** the 2-top seated first on an empty night; later bookings spread out from it */
  first_table: number | null;
  /** how many dedicated 4-tops the room has (0 until they arrive); parties of 3–4 take one before combining 2-tops */
  four_tops: number | null;
  /** the table number of the first 4-top; the rest count up from it */
  four_top_start: number | null;
  /** communal tables take parties of 5 up to max_party */
  communal_tables: number | null;
  /** seats at the bar (B1, B2, …), one guest each; booked only when a guest picks the bar, never as overflow from the dining room. 0 hides the choice */
  bar_seats: number | null;
  /** the largest party the form accepts */
  max_party: number | null;
  /** parties of this size or more see large_party_notice before booking and are told we'll reach out to confirm */
  large_party_min: number | null;
  large_party_notice: string | null;
  /** the whole JSON key of a Google service account with the Sheets API enabled, shared on the spreadsheet as an Editor */
  google_service_account: string | null;
  /** the id from the spreadsheet's URL: docs.google.com/spreadsheets/d/<id>/edit */
  reservations_sheet_id: string | null;
  /** shared with the Square order webhook (nice-dream-kds-ingest), which sends it to hold a table the moment a walk-in is seated; walk-ins are refused while this is blank */
  walk_in_key: string | null;
  /** a Square access token that can read orders; with square_location_id set, a table with an open check in Square can't be booked online */
  square_access_token: string | null;
  /** the Square location whose open checks are read */
  square_location_id: string | null;
  /** seating windows; days uses the same shorthand as business.hours, first/last are the first and last seating as 24h HH:MM */
  seatings: DinnerSeatingsObject[];
  /** booking length by party size, overriding hold_minutes; parties is a size ("5"), a range ("1-2", "6-8") or open-ended ("6+"). The first matching row wins */
  hold_overrides: DinnerHoldOverridesObject[];
  /** staff emailed a summary of every booking the form takes, from reservation@nice-dream.com */
  reservation_emails: DinnerReservationEmailsObject[];
}

// Child objects are read from their parent's file, so they have no path/order.
/** seating windows; days uses the same shorthand as business.hours, first/last are the first and last seating as 24h HH:MM */
export interface DinnerSeatingsObject {
  days: string | null;
  first: string | null;
  last: string | null;
}

// Child objects are read from their parent's file, so they have no path/order.
/** booking length by party size, overriding hold_minutes; parties is a size ("5"), a range ("1-2", "6-8") or open-ended ("6+"). The first matching row wins */
export interface DinnerHoldOverridesObject {
  parties: string | null;
  hold_minutes: number | null;
}

// Child objects are read from their parent's file, so they have no path/order.
/** staff emailed a summary of every booking the form takes, from reservation@nice-dream.com */
export interface DinnerReservationEmailsObject {
  email: string | null;
}

export interface BusinessObject {
  /** `<object name>/<file name>` this object was read from. */
  path: string;
  /** The object's `order`, or null when it is unordered. */
  order: number | null;
  name: string | null;
  description: string | null;
  street_address: string | null;
  locality: string | null;
  region: string | null;
  postal_code: string | null;
  country: string | null;
  phone: string | null;
  /** free text, e.g. "Japanese, Californian" */
  cuisine: string | null;
  /** dollar signs ("$" to "$$$$") or a range like "$15-40" */
  price_range: string | null;
  hours_note: string | null;
  /** days uses schema.org openingHours shorthand (Mo Tu We Th Fr Sa Su, ranges like Fr-Sa); opens/closes are 24h HH:MM, blank opens means closed */
  hours: BusinessHoursObject[];
}

// Child objects are read from their parent's file, so they have no path/order.
/** days uses schema.org openingHours shorthand (Mo Tu We Th Fr Sa Su, ranges like Fr-Sa); opens/closes are 24h HH:MM, blank opens means closed */
export interface BusinessHoursObject {
  label: string | null;
  days: string | null;
  opens: string | null;
  closes: string | null;
}

/** Every object in the site, keyed by name. */
export interface ArchivalObjects {
  about: AboutObject;
  lunch: LunchObject;
  dinner: DinnerObject;
  business: BusinessObject;
}

import type { CarrierEnv } from "@archival/carrier";

declare module "@archival/carrier" {
  interface SiteObjects extends Omit<ArchivalObjects, keyof CarrierEnv> {}
}
